# This is a basic workflow to help you get started with Actions

name: IssueNotify

# Controls when the workflow will run
on:
  issues:
    types: [opened, edited, milestoned]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_MESSAGE: ${{ github.event.issue.body }}
        SLACK_TITLE: ${{ github.event.issue.title }}
